### ISSUE TITLE
CTC + CE Loss 관련해서 질문 있습니다!

### ISSUE THREAD

**Issue by sooftware** [AppleHolic/2020AIChallengeSpeechRecognition#2]
안녕하세요 일지님.  
다름이 아니라, CTC + CE joint training 관련 질문 및 문의사항이 있어서 이슈 남깁니다.  
  
일지님이 공개해주신 자료 덕분에 잘 공부하고 있습니다 ㅎㅎ  
특히 CTC + CE Joint 쪽을 KoSpeech에 옵션으로 추가해봤습니다.  
먼저 허락을 구해야하는데, 제가 실험해보고 싶은 욕심에 깃허브에 반영을 해버렸습니다. 
README.md에 참고 깃허브 링크를 남겨두고 해당 소스를 참고해서 반영해도 괜찮을까요??    
문제가 된다면 해당 코드는 삭제하겠습니다.
  
그리고 추가적인 질문으로는 제가 나름 코드를 적용해서 돌려봤는데, CTC + CE Loss 과정에서 CTC loss가 Inf로 발산해버려서 학습이 되지 않고 있습니다.  
혹시 일지님도 이런 트러블 슈팅이 있으셨을까요??  
  
단위를 그래핌으로 하셨던데, 제가 실험한 환경은 케릭터 기반으로 실험했습니다. CTC가 보캡 사이즈에 영향도 크게 받기 때문에,  
이 때문인가 싶기도 하여 질문 남깁니다. 전에 선배분께 보캡 사이즈를 10,000으로 학습했을 때 loss가 발산해서 그래핌 단위로 했다는 얘기를 들었습니다.  
  
좋은 자료 오픈해주신 점 감사드리며, 이슈 답변 남겨주신다면 많은 도움이 될 것 같습니다.
감사합니다.

**Comment by AppleHolic** [comment]
@sooftware Open license로 한거라 코드 활용 아무렇게나 하셔도 상관없어요ㅎㅎ 참고가 되었다니 다행이네요 . 

 loss 가 inf로 가는건 코드를 보지 않은 상태에서 예측할 수 있는 주요 원인은 데이터 처리에 대한 실수가 있지 않았을까 싶은데, feature에 normalization을 안하거나, wave 또는 label이 배치 처리하다 모두 0으로 가거나, feature-label mismatch하는 문제가 있거나 할 것 같아요. 

 데이터를 그래핌으로 처리했던 이유는,  경진대회 데이터셋이 많은 양의 데이터는 아니었어서, 사전 단위로 학습이 잘 안되었었어요. 구현 해보고 현상에 대한 추론을 해봤었는데,  음성인식 모델 몇개를 구현만 했지 연구를 해본게 아니라 근거가 되는 내용은 모르지만 grapheme의 dimension과 사전의 dimension 차이로 인해 오는 요구 데이터량의 증가가 원인으로 여겼었어요. 사전이 일반적으로 훨씬 많은 라벨 종류를 가지게 되고, 특히 인식은 라벨의 시퀀스로 이루어져 있어서, 사전이 정확한 캐릭터를 제시 해 줄 순 있지만 학습을 위해서 최소한으로 요구되는 데이터 양이 훨씬 많았을 것으로 생각해요 ㅎㅎ  아마 오디오 및 텍스트 데이터의 경우에 따라 유리한 학습이 갈리게 되리라 생각 되네요.

**Comment by sooftware** [comment]
@AppleHolic 답변해주셔서 감사합니다!  
한번 디버그를 해봐야겠네요.   
답변해주신 내용 많은 도움 됐습니다.
  
감사합니다.

**Comment by sooftware** [comment]
@AppleHolic 말씀해주시대로, 확인해봤더니 데이터쪽에 제가 전처리에서 오류난 파일을 사용했더라구요.  
데이터를 다시 정리하고 실행하니 제대로 수렴하네요 감사합니다 ㅎㅎ

**Comment by sooftware** [comment]
@AppleHolic 이후에 다시 loss가 터졌는데, 알고보니 CTC Loss를 계산할 때, 인풋이 아웃풋보다 짧은 경우 나는 문제네요.  
nn.CTCLoss()의 zero_infinite=True로 옵션을 줬더니 정상 동작합니다. ㅎㅎ
